name: CloudMusic CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build --build-arg {{ secrets.SERVER_API }} -t cloud-music .
      - name: Tags
        run: |
          docker tag cloud-music ${{ secrets.DOCKER_USER }}/cloud-music:${{ github.sha }}
          docker tag cloud-music ${{ secrets.DOCKER_USER }}/cloud-music:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/cloud-music:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/cloud-music:latest

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Copy scripts to ssh
        run: |
          scp -i {{ secrets.SERVER_SSH_KEY }} -r ./scripts  {{ secrets.REMOTE_USER }}@{{ secrets.REMOTE_HOST }}:/root/code/
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd $HOME/code/scripts
            ./start.sh
