name: CloudMusic CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t cloud-music .
      - name: Tags
        run: |
          docker tag cloud-music ${{ secrets.DOCKER_USER }}/cloud-music:${{ github.sha }}
          docker tag cloud-music ${{ secrets.DOCKER_USER }}/cloud-music:latest
      - name: push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/cloud-music:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/cloud-music:latest

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: ssh-login
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
